name: Docker Image CI

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ "trunk" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/openplaceguide/opg-pages:latest
          # Check if this is a tag push
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "Tag push detected. Pushing the Docker image..."
            docker push ghcr.io/openplaceguide/opg-pages:latest
          else
            echo "Not a tag push. Skipping Docker push."
          fi
