name: Docker Image CI

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ "trunk" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build the Docker image
        run: |
          # Check if this is a tag push
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Extract tag name from the ref
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "Tag push detected: $TAG_NAME"

            # Build the image
            docker build . --file Dockerfile --tag ghcr.io/openplaceguide/opg-pages:$TAG_NAME

            # Tag it as latest as well
            docker tag ghcr.io/openplaceguide/opg-pages:$TAG_NAME ghcr.io/openplaceguide/opg-pages:latest

            # Push both tags
            echo "Pushing Docker image with tag: $TAG_NAME"
            docker push ghcr.io/openplaceguide/opg-pages:$TAG_NAME
            echo "Pushing Docker image with tag: latest"
            docker push ghcr.io/openplaceguide/opg-pages:latest
          else
            # Just build for PR testing
            echo "Not a tag push. Building image for testing only."
            docker build . --file Dockerfile --tag ghcr.io/openplaceguide/opg-pages:test
          fi
